### ISSUE TITLE
Getting fatal error when running Migration scripts

### ISSUE THREAD

**Issue by zaifastafa** [magento/code-migration#103]
`Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Seri
alize\SerializerInterface in C:\wamp\www\code-migration-develop\vendor\magento\f
ramework\ObjectManager\Factory\Dynamic\Developer.php:50
Stack trace:
#0 C:\wamp\www\code-migration-develop\vendor\magento\framework\ObjectManager\Obj
ectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->c
reate('Magento\\Framewo...')
#1 C:\wamp\www\code-migration-develop\vendor\magento\framework\Config\Data\Scope
d.php(84): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo.
..')
#2 C:\wamp\www\code-migration-develop\vendor\magento\framework\App\ResourceConne
ction\Config.php(52): Magento\Framework\Config\Data\Scoped->__construct(Object(M
agento\Framework\App\ResourceConnection\Config\Reader\Proxy), Object(Magento\Fra
mework\Config\Scope), Object(Magento\Framework\App\Cache\Type\Config\Proxy), 're
sourcesCache', NULL)
#3 C:\wamp\www\code-migration-develop\vendor\magento\framework\ObjectManager\Fac
tory\AbstractFactory.php(111): Ma in C:\wamp\www\code-migration-develop\vendor\m
agento\framework\ObjectManager\Factory\Dynamic\Developer.php on line 50`

**Comment by simonrl** [comment]
Same error here, did you solve this?

**Comment by sopedro** [comment]
Same Here. Any news about this??

**Comment by zaifastafa** [comment]
Nope. Nothing yet.

**Comment by ponrajpushpa** [comment]
I got the same error. now I fixed that error. Check  https://github.com/magento/code-migration/pull/104/files

**Comment by shanevbg** [comment]
Add to app/etc/di.xml in @ ~ line 91
    <preference for="Magento\Framework\Serialize\SerializerInterface" type="Magento\Framework\Serialize\Serializer\Json" />

**Comment by EustaceCS** [comment]
> Add to app/etc/di.xml in @ ~ line 91
> ` <preference for="Magento\Framework\Serialize\SerializerInterface" type="Magento\Framework\Serialize\Serializer\Json" />`

It works for me, thank you!
