### ISSUE TITLE
Code Migration Not Working in Ubuntu

### ISSUE THREAD

**Issue by jaydipsinh8** [magento/code-migration#24]
I have put the code migration tool to my root installation of the LAMP. Then i have run the command called "sudo bin/migrate.php migrateModuleStructure" but it is giving the error sudo: migrate.php: command not found. Can you please let me know what is problem with that

**Comment by sshymko** [comment]
Please run the command via the PHP interpreter:
```
php bin/migrate.php migrateModuleStructure
```

**Comment by sshymko** [comment]
Please keep in mind that the tool is intended for developers. One should not expect a converted code to be fully functional. The goal of the tool is to release a developer from doing routine replacements in the source code during manual process of code migration. Developer expertise in PHP and Magento is required to troubleshoot and fix remaining issues after the tool execution.

**Comment by sshymko** [comment]
Closing as the tool clearly runs on the *nix environments, including Ubuntu.
