### ISSUE TITLE
PHP 7 support and update M2 2.0.5?

### ISSUE THREAD

**Issue by craigcarnell** [magento/code-migration#32]
composer install

```
    - This package requires php ~5.5.0|~5.6.0 but your PHP version (7.0.2) does not satisfy that requirement.
```

**Comment by bordeo** [comment]
Same problem, this project doesn't work with php 7.
I have to switch to php5. use [phpbrew](https://github.com/phpbrew/phpbrew) to manage your php version, it work very well

**Comment by gordonknoppe** [comment]
Upgraded M2 framework and support for PHP7 in #46

**Comment by craigcarnell** [comment]
@gordonknoppe Thank you 👍
