### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by jeremyBass** [magento/code-migration#34]
Hello,
I am not at all sure from the current instructions what to really do.  I'm stuck at, **"•Designated source (Magento 1.x) and target (Magento 2.0) directories"** to which I have been trying to figure out, where?  How to is designate the two?  I see no file that would indicate where.  Not seeing any CLI or anything that leads me to the where/how/what.  Can edits be made to the step by step that assumes the dev is drunk and needs to literally have a step by step :D .

**Comment by twosg** [comment]
Hi, I am also struggling with the directories.

What I have found out so far, is that you use 
`bin/migrate.php migrateModuleStructure <SOURCE_DIR> <TARGET_DIR>`
where SOURCE_DIR is the "Magento root" of your source module. It will expect to have a subdir "app" within it. TARGET_DIR is the installation root of the migration tool. So it can be "." or "../" (when you are inside bin folder).

However for the "createLayout" method, providing the SOURCE_DIR will not work. This method accepts only one argument. I tried providing the original source dir, the layout dir of the source and the source and layout directories of the TARGET_DIR used above. Nothing works. :(

**Comment by deja12** [comment]
Simple Install

1) Download as a zip. unzip and upload it to your home/user/ directory not in public_html or other rootdoc directory.

2) login to your server via shell

3) switch to the code-migration-develop directory by running following command

`cd code-migration-develop`

4) Run command following command in root directory of this toolkit

`composer install`

5) then 

`cd bin`

6)

`php migrate.php migrateModuleStructure /home/user/public_html/MAGENTO_DIR ../`

It will convert the structure and you will see these converted structure in 

code-migration-develop/app/code

7) Run 

`php migrate.php convertLayout ../`

8) Run

`migrate.php convertPhpCode ../`

your code convert completed.

I am not expert but I have done so successfully.

Thanks

**Comment by jeremyBass** [comment]
I will give that a go, but that so far is a clearer path, and could assume I am drunk haha.. thank you

**Comment by sshymko** [comment]
Hi,

The installation and usage instructions in [README.md](../blob/develop/README.md) have been updated.
The confusion around prerequisite directories has beed [explicitly addressed](../blob/develop/README.md#prerequisite-directories).
Please re-read the documentation and let me know if that helps.

Thanks

**Comment by sshymko** [comment]
Closing assuming the issue has been resolved.

**Comment by tinelps** [comment]
@sshymko @deja12 

hi there
i am facing a problem at

**4) Run command following command in root directory of this folder**

1. When i run `composer install`,

it requires me username and password, saying
`Authentication required (repo.magento.com)` ,

and i tried a few attemps, it just says

`Invalid credential for https://repo.magento.com/packages.json, aborting.`

2. Also, the cmd doesn't allow me to type anything at the password.

Can anyone help me with this? i have done little research about the username and password on internet..

> https://community.magento.com/t5/Just-Ask-Alan/Invalid-credentials-for-https-repo-magento-com-packages-json/m-p/23820#M127

They suggested to get the private key and public key from my magento marketplace account, i did that but it doesn't work.
