### ISSUE TITLE
How do I install code-migration ?

### ISSUE THREAD

**Issue by Vikram0811** [magento/code-migration#35]
Can someone list out steps involved to install code-migration toolkit from github ? I am new to this and unaware on how to proceed ?

The instructions written are unclear to me.

Thanks.

**Comment by deja12** [comment]
Simple Install

1) Download as a zip. unzip and upload it to your home/user/ directory not in public_html or other rootdoc directory.

2) login to your server via shell

3) switch to the code-migration-develop directory by running following command

`cd code-migration-develop`

4) Run command following command in root directory of this toolkit

`composer install`

5) then 

`cd bin`

6)

`php migrate.php migrateModuleStructure /home/user/public_html/MAGENTO_DIR ../`

It will convert the structure and you will see these converted structure in 

code-migration-develop/app/code

7) Run 

`php migrate.php convertLayout ../`

8) Run

`migrate.php convertPhpCode ../`

your code convert complete.

I am not expert but I have done so successfully.

Thanks

**Comment by deepjoshi94** [comment]
Can someone let me know about following queries-

- Weather sql files will be migrated or not?

- About the file structure in etc weather it will be converted as per mage 2 standards?

- After the maximum possible migration successfully migrated how much changes are needed and where?

Thanks for support.

**Comment by sshymko** [comment]
Hi,

The installation and usage instructions in [README.md](../blob/develop/README.md) have been updated.
The confusion around prerequisite directories has beed [explicitly addressed](../blob/develop/README.md#prerequisite-directories).
Please re-read the documentation and let me know if that helps.

Thanks

**Comment by sshymko** [comment]
@deepjoshi94,
- SQL files are not covered by the tool at the moment
- Part of configuration files in module's `etc` directory will be migrated
- It depends on how the subject module was architected, there's no definitive answer

**Comment by Richardmaximun** [comment]
Installation and usage instructions in README.md is not clear.
the PREREQUISITE DIRECTORIES section show:

> <src> - Directory that contains custom Magento 1.x code that is intended to be migrated. The code must follow the Magento 1.x directory structure. Magento 1.x core files must not be included.

But the <src> folder is not an empty folder. It come with "Controller class migration tool"

Where i must upload my source files then?

Thanks

**Comment by sshymko** [comment]
@Richardmaximun ,
The [prerequisite directories](https://github.com/magento/code-migration/blob/develop/README.md#prerequisite-directories) are separate directories that you create anywhere in the file system. They are not part of the directory where you choose to install the tool. Directory `<src>` can be any directory, for example, `/Users/someuser/Documents/magento1module/`. That is where you should upload your source files.

Let me know if that helps and how the documentation should be adjusted to convey the information better.

**Comment by sshymko** [comment]
Closing assuming the issue has been resolved.

**Comment by sshymko** [comment]
FYI: My presentation on the tool at Imagine 2016 8-)

**Comment by tinelps** [comment]
@sshymko @deja12

hi there
i am facing a problem at

4) Run command following command in root directory of this folder

When i run composer install,
it requires me username and password, saying
Authentication required (repo.magento.com) ,

and i tried a few attemps, it just says

Invalid credential for https://repo.magento.com/packages.json, aborting.

Also, the cmd doesn't allow me to type anything at the password.
Can anyone help me with this? i have done little research about the username and password on internet..

https://community.magento.com/t5/Just-Ask-Alan/Invalid-credentials-for-https-repo-magento-com-packages-json/m-p/23820#M127
They suggested to get the private key and public key from my magento marketplace account, i did that but it doesn't work.

**Comment by sshymko** [comment]
@tinelps 
I believe these are the keys issued by the new Magento marketplace https://marketplace.magento.com/.
Please follow the guide http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html.

**Comment by tinelps** [comment]
Hi there, i'm able to run `composer install`.
However, i have this problem during installing. It says `Full extraction path exceed MAXPATHLEN (260)`. I believe it is the name too long. How do I solve this issue?
And, in the picture below, there are a few **"failed message"** such as `failed to download psr/log`. What does that mean? I have highlighted it below.

![capture2](https://cloud.githubusercontent.com/assets/19793078/16035832/c3245b48-324b-11e6-8aa1-b0c2c1654a8f.PNG)
