### ISSUE TITLE
migrateModuleStructure not creating any files

### ISSUE THREAD

**Issue by saiyadsalma** [magento/code-migration#37]
Hello  i have installed my 1.9.2.4 installation under /var/www/html/magento/ directory and on same directory there is installation of 2.0.2. 
After that i have moved code-migration to same directory but when i ran the following command it wont create any files under code-migration-develop/app.
**root@TSS71:/var/www/html/magento/code-migration-develop#** php bin/migrate.php migrateModuleStructure ../1.9.2.4/ ../2.0.2/

Please help me out to find out proper way to migrate on linux system.

**Comment by sshymko** [comment]
Hi,

The installation and usage instructions in [README.md](../blob/develop/README.md) have been updated.
The confusion around prerequisite directories has beed [explicitly addressed](../blob/develop/README.md#prerequisite-directories).
Please re-read the documentation, it should help.

Thanks

**Comment by sshymko** [comment]
Closing assuming the issue has been resolved.
