### ISSUE TITLE
Can I Maigrate Single Magento 1.x module to magento 2

### ISSUE THREAD

**Issue by Git-Rajkumar** [magento/code-migration#38]
Hello, 
   I installed magento 2 in locally , its working fine, but, I download one Magento 1.x custom module called live chat extension, I need to migrate this module to magento 2, can I do it using your migration tool, if fail means , which way to do it, suggest me.

and also, 
 send me any opensource live chat extenstion there in magento 2. 

Thanks in advance

**Comment by sshymko** [comment]
Hello,

The code migration tool is intended for Magento developers with expertise in Magento 1.x and Magento 2 architecture. Module migration will require some manual work. Btw, the documentation in [README.md](../blob/develop/README.md) has been recently updated, it should clarify some usage questions.

Thanks

**Comment by sshymko** [comment]
Hi,

Regarding the live chat module question.
http://magento.stackexchange.com/ would be a better resource to ask that question.
Closing the GitHub ticket.

Thanks

**Comment by Git-Rajkumar** [comment]
Hello sshymko,
Thanks for your Suggestion
