### ISSUE TITLE
PHP Fatal error:  Call to a member function children() on null in code-migration/src/Magento/Migration/Utility/M1/Config.php on line 128

### ISSUE THREAD

**Issue by markhilton** [magento/code-migration#44]
last migration step: php bin/migrate.php convertPhpCode <dst> <m1> <m2>

[WARNING]: <?xml version="1.0"?> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">     <default>         <productsharing>             <settings>                 <share_button_class>shopalize-share-icon-24</share_button_class>                 <share_button_text>Share & Save</share_button_text>             </settings>         </productsharing>     </default> </config>  is not a valid xml file or couldn't be loaded

PHP Fatal error:  Call to a member function children() on null in code-migration/src/Magento/Migration/Utility/M1/Config.php on line 128

**Comment by sshymko** [comment]
Obviously there's an invalid XML file (likely `etc/config.xml` in the module) that cannot be parsed :)

**Comment by Rocketship1** [comment]
@sshymko was valid - I have run it thought a different parser to validate. I have worked around the problem by removing the extension.

**Comment by markhilton** [comment]
@sshymko was valid. I have run it though a different parser to confirm. I have worked around the problem by removing the extension.

**Comment by namnn96** [comment]
@markhilton I got the same error, please share how you got over it. 

Thanks in advance
