### ISSUE TITLE
creating custom module in Magento

### ISSUE THREAD

**Issue by inkxe-ramendra** [magento/code-migration#45]
Is it mandatory to give Namespace while creating custom module in Magento ? if No then what  will put  in place on namespace .

**Comment by sshymko** [comment]
Magento 2 follows PSR standards, which require every component to have a top-level namespace that corresponds to the vendor name.
Magento 2 modules have the following directory structure `app/code/<Vendor>/<Module>`.
Placeholder `<Vendor>` represents top-level namespace.
