### ISSUE TITLE
PHP Fatal error:  Class 'Zend\Escaper\Escaper' not found

### ISSUE THREAD

**Issue by Sureshchikani** [magento/code-migration#58]
Hi,

I am getting error "PHP Fatal error:  Class 'Zend\Escaper\Escaper' not found" while run `php bin/migrate.php convertPhpCode dst m1 m2`

Could any one help me to get rid of the issue .

Thanks,

**Comment by gordonknoppe** [comment]
Zend escaper is now added back as a dependency, please re-test and re-open if your issue continues.
