### ISSUE TITLE
 [InvalidArgumentException]   Command "migrateModuleStructure" is not defined.

### ISSUE THREAD

**Issue by brijeshgupta** [magento/code-migration#61]
Hi,

I have download the magneto 2 and copy the migration code in that folder when i run the  "php bin/migrate.php migrateModuleStructure src1 dst" getting the error message "[InvalidArgumentException]  Command "migrateModuleStructure" is not defined. "

Please suggest

**Comment by gordonknoppe** [comment]
The tool should be installed in it's own directory and not copied into your Magento 2 source.
