### ISSUE TITLE
Please suggest where we place migration script

### ISSUE THREAD

**Issue by brijeshgupta** [magento/code-migration#62]
Hi,

I am new in Magneto Please suggest where we need to place this script

1) Magneto 1.x folder
2) Magneto 2.x folder
3) New folder

Thanks in advance

**Comment by gordonknoppe** [comment]
Hello @brijeshgupta the tool should be checked out and installed in it's own directory.

**Comment by brijeshgupta** [comment]
We are getting this "Fatal error: Class 'Zend\Http\PhpEnvironment\Request' not found"

**Comment by brijeshgupta** [comment]
When we install this its own directory  getting this "Fatal error: Class 'Zend\Http\PhpEnvironment\Request' not found"

Need to set any path in env.php ?

**Comment by gordonknoppe** [comment]
Please provide clear steps to reproduce

**Comment by brijeshgupta** [comment]
First download the migration script and unzip under code-migration-develop then run below command
Step 1 : Create a folder src1 with my extension code
Step 2: Create empty dst folder
step 3: m1 folder which contains magneto 1.8 code with my extension 
step 4: m2 folder with magneto 2.0 code
Step 5: php bin/migrate.php migrateModuleStructure src1 dst
Step 6: php bin/migrate.php convertLayout dst
Step 7: php bin/migrate.php convertConfig dst
Step 8: php bin/migrate.php convertPhpCode dst m1 m2
then getting error "Fatal error: Class 'Zend\Http\PhpEnvironment\Request' not found"

**Comment by brijeshgupta** [comment]
Hi,

You can also chk on our server via putty

host - skybox.sappleserve.com
user - skyboxsapple
pass -skybox@123
port :22
path - /home/skyboxsapple/migrate
path to migration toolkit - /home/skyboxsapple/code-migration-develop

**Comment by brijeshgupta** [comment]
Also you can check step by step screen shots.

![1](https://cloud.githubusercontent.com/assets/391773/16694363/6792f8b0-4557-11e6-9890-4aad2b85397b.png)
![2](https://cloud.githubusercontent.com/assets/391773/16694364/6795acd6-4557-11e6-8a6c-aab93d658a68.png)
![3](https://cloud.githubusercontent.com/assets/391773/16694365/67988032-4557-11e6-8cd9-57e9ca9ba8e3.png)

**Comment by brijeshgupta** [comment]
Hello @gordonknoppe  We are waiting for your response, Please do let me know if you need any other details.

Thanks alot,
Brijesh

**Comment by brijeshgupta** [comment]
@gordonknoppe @sshymko  Hello Guys,

Please help us

**Comment by sshymko** [comment]
@brijeshgupta 
It seems to be a bug in the tool, the dependency declaration `zendframework/zend-http` is missing. More interesting question is why this dependency is even needed for the CLI tool.

Please run `composer require zendframework/zend-http 2.4.0` in the tool directory to fix the issue.

**Comment by ubakarasamy** [comment]
i'm getting Fatal error while php migrate.php convertLayout '/var/www/html/codemigration/applicatio'

> PHP Fatal error:  Uncaught Error: Class 'XML_Serializer' not found in /var/www/html/codemigration/code-migration-develop/src/Magento/Migration/Command/ConvertLayout.php:211

Can anyone help me with this
