### ISSUE TITLE
Integration with Travis CI

### ISSUE THREAD

**Issue by sshymko** [magento/code-migration#9]
The tools come with PHPUnit-based tests. In particular, unit and static tests. In order to ensure quality of incoming pull requests, it would be beneficial to implement integration with the Travis CI, similarly to how it's done for [Magento 2 CE repository](https://github.com/magento/magento2).

AC:
- Unit tests run upon every push to the repo
- Static tests run upon every push to the repo
- Badge displaying a state of the latest build on a `develop` branch

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by sshymko** [comment]
Builds on Travis CI [run successfully](https://travis-ci.org/sshymko/code-migration/branches).
